### ISSUE TITLE
A question about the polling methods

### ISSUE THREAD

**Issue by Dmitry1987** [poppyred/python-consul2#1]
Hey I thought I'll ask here because you've invited us all here but here's a bit quiet in the issues! :D 
So I'll be the first.

I'm trying to create a K8s operator, that will poll the key-value in consul. But the code listed on homepage seems like an infinite loop, I mean this one:
```
# poll a key for updates
index = None
while True:
    index, data = c.kv.get('foo', index=index)
    print data['Value']
```

How does it work?  If I run such thing, it will query my Consul cluster a million times per second or it has some underlying magic going on? (would that "index/data" pair be received only once per modification in Consul itself, and the rest of time it will just sleep on that line waiting for next event somehow?)

**Comment by poppyred** [comment]
@Dmitry1987 thankyou give me first issues

**Comment by Dmitry1987** [comment]
oh, I see.. so if I want to poll consul for KV changes all the time (like consul-template does for example) I need to create such infinite loop in another thread, and set the 'wait' interval, so it'll poll each N seconds basically? 
Thanks for the explanation, that was my issue :)  I was unable to understand this method based on the docs. 
So until the index doesn't change - this query will return the same data each time? Which means I need additional app logic, to compare whether the index I got is same as before or not, and by that decide to render the received data or not?

**Comment by poppyred** [comment]
Q1: _oh, I see.. so if I want to poll consul for KV changes all the time (like consul-template does for example) I need to create such infinite loop in another thread, and set the 'wait' interval, so it'll poll each N seconds basically?_
A1: yes
Q2: _So until the index doesn't change - this query will return the same data each time? Which means I need additional app logic, to compare whether the index I got is same as before or not, and by that decide to render the received data or not?_
A2: yes 
If you're pursuing performance you can judge index。 if not, you can pull it every times, index is None every time you pull the current one


you can see the implementation of poll and fetch on [consul-template](https://github.com/hashicorp/consul-template/blob/master/watch/view.go#L194)
