### ISSUE TITLE
Is it possible to fix NODE_META in catalog.register

### ISSUE THREAD

**Issue by fernandino143** [poppyred/python-consul2#11]
This is already mentioend in https://github.com/cablehead/python-consul/pull/273/commits/c01e4bc1e749dd6ffe3640d36622ee367ba038fe, but it seems like python-consul is dead (??). So, the thing is that if one registers a service like:

`def n_meta():
	return {
        "hello": "darkness"
    	}
c.catalog.register(unique_name, ip, service=service, node_meta=n_meta())
`

I'd expect the node_meta to be added to the node (unique_name) associated with the registered service (service). However, from the documentation (and tests), the node_meta is never added to the node since it's meant to be used only for filtering. Meaning, node_meta is kinda useless for filtering since it's never added to the node.

**Comment by poppyred** [comment]
Yes, in data  not in params.
Thank you!  :) @fernandino143

**Comment by fernandino143** [comment]
Nice! I see you got it fixed on 0.0.17.dev0. Beautiful job :)
Any idea when this is going to stable?

**Comment by poppyred** [comment]
It ll be ready in a minute！
@fernandino143 :)

**Comment by fernandino143** [comment]
**You did a fantastic job here**, but, just noticed that this was working on v0.0.17, but, not on v0.1.0+.

From what I noticed, 0.1.0+ doesn't filter, but, instead lists all nodes regardless of node_meta value. And pypi doesn't show 0.0.17 :( 

Did something happen and this had to be rolledback?

**Comment by fernandino143** [comment]
Nevermind. My mistake. This is perfect!!!
