### ISSUE TITLE
add operator endpoints like autopilot and raft

### ISSUE THREAD

**Issue by markblackman** [poppyred/python-consul2#19]
https://www.consul.io/api-docs/operator  both raft and autopilot could do with support.

**Comment by poppyred** [comment]
It has been supported 
[here](https://github.com/poppyred/python-consul2/blob/master/consul/base.py#L3124)

**Comment by markblackman** [comment]
Fantastic, thanks. Sorry, I didn't see it in the in the docs, so I had believed there was no support. I'll consider updating docs then. Great work maintaining this module.

**Comment by poppyred** [comment]
> Fantastic, thanks. Sorry, I didn't see it in the in the docs, so I had believed there was no support. I'll consider updating docs then. Great work maintaining this module.

That would be great work! Thank you :)
