### ISSUE TITLE
consul保持长连接问题

### ISSUE THREAD

**Issue by JSK520** [poppyred/python-consul2#27]
看了下源码，不支持传 request 非长连接的参数，这样对服务来说不太友好。我们方案是首次读consul，然后写文件，隔一段时间创建新连接连接 consul，这会导致两个问题：
1、连接会越来越多
2、一直保持长连接

不想复用连接的原因是：可能有断开的风险，这样代码层面需要考虑过多情况，同时当开启多个进程时，会导致连接过多的情况

我看作者是咱中国同胞，希望加个联系方式沟通

**Comment by poppyred** [comment]
@JSK520 春节快乐!  有参数控制wait时间的.    [这儿](https://github.com/poppyred/python-consul2/blob/master/tests/test_std.py#L33).  373251686@qq.com 邮箱联系哦.
