### ISSUE TITLE
麻蛋，python-consul的包把我坑惨了

### ISSUE THREAD

**Issue by rainmanliu** [poppyred/python-consul2#7]
我发现我改了几个地方，meta，deregister的token，你这边都有，先用你这个包吧，感谢老铁可以继续维护

**Comment by poppyred** [comment]
感谢老铁的星星，会持续维护的，目前兼容问题我在考虑，新老版本api有所变化，未来会分出不同api，尽量使用新版consul使用很稳定。

**Comment by poppyred** [comment]
#8  @rainmanliu  不能使用1.7X版本,consul最新版本如果传递多余字段会400错误。在加紧修复
